---
version: "2.1"
services:
  server:
    image: mc-server
    container_name: minecraft-server
    ports:
      - "25565:25565"
    volumes:
      - ./world:/server/world
      - ./ops.json:/server/ops.json

    restart: unless-stopped
